language: node_js
node_js:
  - 4.4.0

addons:
  apt:
    packages:
      - texlive
      - texlive-latex-extra

before_install:
  - openssl aes-256-cbc -K $encrypted_e5009b71da55_key -iv $encrypted_e5009b71da55_iv
    -in deploy_key.enc -out deploy_key -d
  - rvm install 2.2.2

install:
  - npm install gulp
  - npm install
  - gem install jekyll
  - gem install html-proofer
  - ./_docs.sh depend

script:
  - gulp build
  - npm test

after_success:
  - chmod +x push-build.sh
  - ./push-build.sh

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=tru
    - NODE_ENV=production

# Only build pushes to the master branch, PRs, and branches beginning with `test-`.
branches:
  only:
    - master
    - /^test-.*$/

sudo: required
